@startuml Альтернативная диаграмма компонентов системы мониторинга скота
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Monitoring system backend 

Container(web_app, "Web App", "TypeScript")
Container(mobile_app, "Mobile App", "Swift, Java")

Container_Boundary(backend, "Monitoring system backend"){
    Component(api_gateway, "API Gateway", "Java/Spring")

    Component(login_service, "Сервис авторизации", "Java, Spring")
    Component(registration_service, "Сервис регистрации", "Java, Spring")
    Component(verification_service, "Управление ролями и правами", "Java, Spring")

    Component(event_processing_service, "Сервис обработки событий", "Java, Spring")
    Component(event_analytics_service, "Сервис аналитики событий", "Java, Spring")

    Component(feed_service, "Сервис управления кормушками и поилками", "Java, Spring")
    Component(filter_service, "Сервис мониторинга фильтров воды", "Java, Spring")
    Component(monitoring_device_service, "Сервис управления камерами и датчиками", "Java, Spring")

    Component(accounting_service, "Сервис учета запасов и прогнозирования расходов", "Java, Spring")
    Component(sync_service, "Сервис синхронизации данных", "Java, Spring")
    Component(reporting_service, "Сервис составления отчетов", "Java, Spring") 

    Component(notification_service, "Сервис уведомлений", "Java, Spring")

    ComponentDb(metadata_db, "User info and Metadata DB", "PostgreSql")
    ComponentDb(metrics_db, "Metrics DB", "Сlickhouse")
    ComponentDb(video_photo_db, "Video and screenshots DB", "S3")
    ComponentDb(event_db, "Event DB", "Clickhouse")
}
Container_Boundary(devices, "Датчики и камеры"){
    Container(камеры, "Камеры")
    Container(датчики, "Датчики с животных и полей", "Python")
    Container(кормушки, "Кормушки", "Python")
    Container(поилки, "Поилки", "Python")
}

ContainerQueue(kafka, "Message queue", "Kafka")
Container_Ext(analytics, "Аналитический модуль")
Container(stream_processor, "Потоковый обработчик", "Kafka Streams")
Container(rules_engine, "Движок правил", "Esper/Hazelcast")

Rel(web_app, api_gateway, "Авторизация и аутентификация")
Rel(mobile_app, api_gateway, "Авторизация и аутентификация")

'Авторизация и аутентификация
Rel(api_gateway, login_service, "API авторизации")
Rel(api_gateway, registration_service, "API регистрации")
Rel(api_gateway, verification_service, "API аутентификации")
Rel(login_service, metadata_db, "Передает и читает данные")
Rel(registration_service, metadata_db, "Передает и читает данные")
Rel(verification_service, metadata_db, "Передает и читает данные")

'Настройка кормушек, поилок, датчиков и камер
Rel(mobile_app, feed_service, "Использует API")
Rel(mobile_app, filter_service, "Использует API")
Rel(mobile_app, monitoring_device_service, "Использует API")

'Просмотр метрик
Rel(web_app, reporting_service, "Запрашивает и составляет метрики")
Rel(web_app, accounting_service, "Запрашивает данные")

'Внутренние коммуникации
Rel(event_processing_service, kafka, "читает сообщения")
Rel(event_processing_service, event_db, "Сохраняет и запрашивает события")
Rel(event_analytics_service, event_db, "Анализирует метрики")
Rel(rules_engine, notification_service, "Отправляет уведомления")

Rel(reporting_service, event_db, "Запрашивает данные для метрик")
Rel(reporting_service, metrics_db, "Сохраняет метрики")

Rel(accounting_service, metrics_db, "Запрашивает данные для прогнозирования")
Rel(sync_service, metadata_db, "Запрашивает метаданные для синхронизации")
Rel(sync_service, metrics_db, "Запрашивает метрики для синхронизации")

Rel(notification_service, kafka, "Читает сообщения")

@enduml