@startuml Диаграмма компонентов системы мониторинга скота
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Monitoring system backend 

Container(web_app, "Web App", "TypeScript")
Container(mobile_app, "Mobile App", "Swift, Java")

Container_Boundary(backend, "Monitoring system backend"){
    Component(api_gateway, "API Gateway", "Java/Spring")

    Component(login_service, "Сервис авторизации", "Java, Spring")
    Component(registration_service, "Сервис регистрации", "Java, Spring")
    Component(verification_service, "Управление ролями и правами", "Java, Spring")

    Component(behavior_analyzer_service, "Анализ поведения животных", "Java, Spring")
    Component(health_analyzer_service, "Оценка здоровья животных", "Java, Spring")
    Component(population_analyzer_service, "Подсчет поголовья стада", "Java, Spring")

    Component(feed_service, "Сервис управления кормушками и поилками", "Java, Spring")
    Component(filter_service, "Сервис мониторинга фильтров воды", "Java, Spring")
    Component(monitoring_device_service, "Сервис управления камерами и датчиками", "Java, Spring")

    Component(accounting_service, "Сервис учета запасов и прогнозирования расходов", "Java, Spring")

    Component(metrics_service, "Сервис управления и сбора метрик", "Java, Spring")
    Component(video_processing_service, "Сервис обработки видео", "Java, Spring")
    Component(sensor_processing_service, "Сервис обработки данных с датчиков", "Java, Spring")

    Component(sync_service, "Сервис синхронизации данных", "Java, Spring")

    Component(notification_service, "Сервис уведомлений", "Java, Spring")

}

Container_Boundary(devices, "Датчики и камеры"){
    Container(камеры, "Камеры")
    Container(датчики, "Датчики с животных и полей", "Python")
    Container(кормушки, "Кормушки", "Python")
    Container(поилки, "Поилки", "Python")
}

ContainerDb(metadata_db, "User info and Metadata DB", "PostgreSql")
ContainerDb(metrics_db, "Metrics DB", "Сlickhouse")
ContainerDb(video_photo_db, "Video and screenshots DB", "S3")

ContainerQueue(kafka, "Message queue", "Kafka")
Container_Ext(analytics, "Аналитический модуль")

Rel(web_app, api_gateway, "Авторизация и аутентификация")
Rel(mobile_app, api_gateway, "Авторизация и аутентификация")

'Авторизация и аутентификация
Rel(api_gateway, login_service, "API авторизации")
Rel(api_gateway, registration_service, "API регистрации")
Rel(api_gateway, verification_service, "API аутентификации")
Rel(login_service, metadata_db, "Передает и читает данные")
Rel(registration_service, metadata_db, "Передает и читает данные")
Rel(verification_service, metadata_db, "Передает и читает данные")

'Настройка кормушек, поилок, датчиков и камер
Rel(mobile_app, feed_service, "Использует API")
Rel(mobile_app, filter_service, "Использует API")
Rel(mobile_app, monitoring_device_service, "Использует API")

'Просмотр метрик
Rel(web_app, metrics_service, "Запрашивает и составляет метрики")

'Внутренние коммуникации
Rel(devices, video_processing_service, "Передает видеопоток")
Rel(devices, sensor_processing_service, "Передает данные")

Rel(video_processing_service, kafka, "Публикует сообщения")
Rel(video_processing_service, video_photo_db, "Сохраняет видео и скриншоты")
Rel(sensor_processing_service, kafka, "Публикует сообщения")
Rel(sensor_processing_service, metrics_db, "Сохраняет метрики")

Rel(behavior_analyzer_service, kafka, "Читает события поведения")
Rel(health_analyzer_service, kafka, "Читает данные о состоянии здоровья")
Rel(population_analyzer_service, kafka, "Читает данные подсчета")

Rel(behavior_analyzer_service, kafka, "Публикует агрегированные данные поведения")
Rel(health_analyzer_service, kafka, "Публикует агрегированные данные здоровья")
Rel(metrics_service, kafka, "Читает агрегированные данные")
Rel(metrics_service, analytics, "Передает данные")
Rel(metrics_service, metrics_db, "Сохраняет метрики")

Rel(accounting_service, metrics_db, "Запрашивает данные для прогнозирования")
Rel(sync_service, metadata_db, "Запрашивает метаданные для синхронизации")
Rel(sync_service, metrics_db, "Запрашивает метрики для синхронизации")

Rel(notification_service, kafka, "Читает сообщения")

@enduml