@startuml Контекстная диаграмма системы мониторинга скота
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Контекстная диаграмма системы мониторинга скота

Person(директор, "Директор хозяйства")
Person(управляющий, "Управляющий животноводческим комплексом")
Person(животновод, "Животновод")
Person(оператор, "Оператор")
Person(зоотехник, "Зоотехник")
Person(ветеринар, "Ветеринар")

System(PigMonitoringSystem, "Система мониторинга скота", "Управление животноводческим комплексом")
System_Ext(аналитика, "Аналитический модуль")
System_Ext(уведомления, "Система отправки уведомлений")
System_Ext(камеры, "Камеры")
System_Ext(датчики_животные, "Датчики на животных")
System_Ext(датчики_загоны, "Датчики на загонах")

Rel(директор, PigMonitoringSystem, "Получает отчеты по состоянию животноводческого комплекса")
Rel(управляющий, PigMonitoringSystem, "Получает оперативные отчеты, ставит задачи")
Rel(оператор, PigMonitoringSystem, "Настраивает систему, контролирует работу датчиков")
Rel(зоотехник, PigMonitoringSystem, "Настраивает автоматические кормушки и поилки в соответствии с планом, следит за активностью и нормами кормления, мониторит активность животных")
Rel(ветеринар, PigMonitoringSystem, "Следит за показателями здоровья животных")
Rel(животновод, PigMonitoringSystem, "Следит за сигналами, требующими срочного вмешательства")

Rel(датчики_животные, PigMonitoringSystem, "Передает данные о месторасположении и состоянии животных")
Rel(датчики_загоны, PigMonitoringSystem, "Передает данные о месторасположении животных")
Rel(камеры, PigMonitoringSystem, "Передает видеопоток и изображения для анализа")
Rel(PigMonitoringSystem, аналитика, "Передает агрегированные и структурированные данные для долгосрочного анализа")
Rel(PigMonitoringSystem, уведомления, "Передает текст сообщений и получателя")

@enduml