@startuml Контекстная диаграмма системы мониторинга скота
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Контекстная диаграмма системы мониторинга скота

Person(администратор, "Директор хозяйства, управляющий", "Получает отчеты и сводки")
Person(менеджер, "Зоотехники, ветеринары, операторы", "Настраивают систему, мониторят показатели")
Person(животновод, "Животновод", "Следит за сигналами, требующими вмешательства")

System_Boundary(PigMonitoringSystem, "Система мониторинга скота", "Управление животноводческим комплексом") {
    System(central, "Центральный сервер", "Агрегирует данные со всех ферм")
    System(нейросеть, "Локальная нейросеть", "Анализ видеопотока в реальном времени")
    System(farm, "Ферма (Edge-сервер)")
    System_Boundary(iot, "Внешние источники данных"){
        System(датчики_животные, "Датчики на животных")
        System(датчики_загоны, "Датчики на загонах")
        System(камеры, "Камеры")
    }
}

System_Ext(аналитика, "Аналитический модуль")
System_Ext(уведомления, "Провайдер отправки уведомлений")

Rel(администратор, central, "Получает отчеты по состоянию животноводческого комплекса, ставит задачи")
Rel(менеджер, central, "Настраивает систему, контролирует работу датчиков, настраивает автоматические кормушки и поилки, следит за нормами кормления, следит за показателями злоровья")
Rel(животновод, farm, "Следит за сигналами, требующими срочного вмешательства")

Rel(iot, farm, "Передает данные о месторасположении животных и внешней среде, видеопоток и изображения для анализа")
Rel(farm, central, "Синхронизирует данные (задержка до 10 мин.). Передает агрегированные данные")
Rel(farm, central, "Альтернативный канал связи 4G/LTE")
Rel(farm, нейросеть, "Передает видеоданные для анализа в реальном времени")
Rel(central, аналитика, "Передает агрегированные и структурированные данные для долгосрочного анализа")
Rel(farm, уведомления, "Передает текст сообщений и получателя")

@enduml