@startuml Контекстная диаграмма системы мониторинга скота
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Контекстная диаграмма системы мониторинга скота

Person(администратор, "Директор хозяйства, управляющий", "Получает отчеты и сводки")
Person(менеджер, "Зоотехники, ветеринары, операторы", "Настраивают систему, мониторят показатели")
Person(животновод, "Животновод", "Следит за сигналами, требующими вмешательства")

System(PigMonitoringSystem, "Система мониторинга скота", "Управление животноводческим комплексом")
System_Ext(аналитика, "Аналитический модуль")
System_Ext(уведомления, "Система отправки уведомлений")
 System_Boundary(iot, "Внешние источники данных"){
    System_Ext(датчики_животные, "Датчики на животных")
    System_Ext(датчики_загоны, "Датчики на загонах")
    System_Ext(камеры, "Камеры")
}

Rel(администратор, PigMonitoringSystem, "Получает отчеты по состоянию животноводческого комплекса, ставит задачи")
Rel(менеджер, PigMonitoringSystem, "Настраивает систему, контролирует работу датчиков, настраивает автоматические кормушки и поилки, следит за нормами кормления, следит за показателями злоровья")
Rel(животновод, PigMonitoringSystem, "Следит за сигналами, требующими срочного вмешательства")

Rel(iot, PigMonitoringSystem, "Передает данные о месторасположении животных и внешней среде, видеопоток и изображения для анализа")
Rel(PigMonitoringSystem, аналитика, "Передает агрегированные и структурированные данные для долгосрочного анализа")
Rel(PigMonitoringSystem, уведомления, "Передает текст сообщений и получателя")

@enduml